version: "1.1"

services:
  node:
    container_name: andymobile-backend
    restart:  always
    image: node:20.9.0
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app
    working_dir:  /usr/src/app

    networks:
      - andymobile_network
    # PRODUCTION
    command: bash -c "npm install && npm run start:prod"

    # DEVELOPMENT
    # command: bash -c "npm install && npm run dev"

networks:
  andymobile_network:
    driver: bridge